[package]
edition = "2024"
license = "Apache-2.0"
name = "veecle-os-examples-freertos-linux"
publish = false
version = "0.0.0"

[workspace]

[dependencies]
veecle-freertos-integration = { version = "0.1.1", default-features = false, features = [
  "link-freertos",
  # SAFETY: we use the same prototype in `FreeRTOSConfig.h` as required by this feature.
  "unsafe-hooks-assert",
] }
veecle-os = { path = "../../veecle-os", default-features = false, features = ["osal-freertos", "telemetry-enable"] }
veecle-os-examples-common = { path = "../common", default-features = false, features = ["alloc", "telemetry"] }
# TODO: Necessary for thread-local right now.
rand = { version = "0.9.2", default-features = false, features = ["std"] }
veecle-telemetry = { path = "../../veecle-telemetry", default-features = false, features = ["std"] }

[dev-dependencies]
assert_cmd = { version = "2.0.17", default-features = false }
predicates = { version = "3.1.3", default-features = false }

[[bin]]
name = "alloc"
path = "src/bin/alloc.rs"
test = false
bench = false

[[bin]]
name = "time"
path = "src/bin/time.rs"
test = false
bench = false

[[bin]]
name = "queues"
path = "src/bin/queues.rs"
test = false
bench = false
