[package]
name = "veecle-os-examples-freertos-linux"
version = "0.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace]

[[bin]]
bench = false
name = "alloc"
path = "src/bin/alloc.rs"
test = false

[[bin]]
name = "time"
path = "src/bin/time.rs"
test = false
bench = false

[[bin]]
name = "queues"
path = "src/bin/queues.rs"
test = false
bench = false

[dependencies]
rand = { version = "0.9.2", default-features = false, features = ["std"] }
veecle-freertos-integration = { version = "0.1.2", default-features = false, features = [
  "link-freertos",
  # SAFETY: we use the same prototype in `FreeRTOSConfig.h` as required by this feature.
  "unsafe-hooks-assert",
] }
veecle-os = { path = "../../veecle-os", default-features = false, features = [
  "osal-freertos",
  "telemetry-enable",
] }
veecle-os-examples-common = { path = "../common", default-features = false, features = [
  "alloc",
] }
veecle-telemetry = { path = "../../veecle-telemetry", default-features = false, features = [
  # TODO: Necessary to activate the feature for thread-local right now, this dependency shouldn't be needed at all.
  "std",
] }

[dev-dependencies]
assert_cmd = { version = "2.0.17", default-features = false }
predicates = { version = "3.1.3", default-features = false }
