exclude = ["*.*/**", "external/submodules/**", "target/**"]

[formatting]
reorder_arrays = true
column_width = 120

[[rule]]
include = ["**/Cargo.toml"]
keys = ["*-dependencies", "*.*.dependencies", "*.dependencies", "dependencies", "features", "package"]

[rule.formatting]
reorder_keys = true

[[rule]]
include = ["clippy.toml"]

[rule.formatting]
array_auto_collapse = false

[[rule]]
include = ["**/book.toml"]

[rule.formatting]
reorder_arrays = false

[[rule]]
include = ["**/about.toml"]
# `accepted` is an order-dependent list so should not be alphabetized.
# TODO(DEV-698): https://github.com/tamasfe/taplo/issues/608 means we can't have other arrays sorted but this not.
# keys = ["accepted"]

[rule.formatting]
reorder_arrays = false
