[package]
name = "veecle-os-crate"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
veecle-os = { path = "../../../veecle-os", features = ["data-support-someip"] }
