[package]
description = "Message definition for the WebSocket tracing data protocol"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "veecle-telemetry-server-protocol"
publish = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[package.metadata]
# This crate uses `#![forbid(unsafe_code)]`.
workspace-checks.miri = false

[package.metadata.docs.rs]
all-features = true

default-target = "x86_64-unknown-linux-gnu"
targets = []

[lints]
workspace = true

[dependencies]
serde = { workspace = true, features = ["std"] }
serde_derive = { workspace = true }
