[package]
name = "veecle-telemetry-server-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Message definition for the WebSocket tracing data protocol"
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish = true

[package.metadata]
# This crate uses `#![forbid(unsafe_code)]`.
workspace-checks.miri = false

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"
targets = []

[dependencies]
serde = { workspace = true, features = ["std"] }
serde_derive = { workspace = true }

[lints]
workspace = true
