inputs:
  cargo-about:
    description: cargo-about
    default: "false"
  cargo-deny:
    description: cargo-deny
    default: "false"
  cargo-llvm-cov:
    description: cargo-llvm-cov
    default: "false"
  cargo-nextest:
    description: cargo-nextest
    default: "false"
  cargo-workspaces:
    description: cargo-workspaces
    default: "false"
  cargo-vet:
    description: cargo-vet
    default: "false"
  convco:
    description: convco
    default: "false"
  taplo-cli:
    description: taplo-cli
    default: "false"
  trunk:
    description: trunk
    default: "false"
  mdbook:
    description: mdbook
    default: "false"
  just:
    description: just
    default: "false"
  fnm:
    description: fnm
    default: "false"
  wasm-pack:
    description: wasm-pack
    default: "false"
runs:
  using: composite
  steps:

    # Cache and install cargo-about
    - uses: actions/cache@v4
      if: inputs.cargo-about == 'true'
      id: cache-cargo-about
      with:
        path: ~/.cargo/bin/cargo-about
        key: cargo-about-0.7.1-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.cargo-about == 'true' && steps.cache-cargo-about.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-about --version 0.7.1 --locked

    # Cache and install cargo-deny
    - uses: actions/cache@v4
      if: inputs.cargo-deny == 'true'
      id: cache-cargo-deny
      with:
        path: ~/.cargo/bin/cargo-deny
        key: cargo-deny-0.18.4-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.cargo-deny == 'true' && steps.cache-cargo-deny.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-deny --version 0.18.4 --locked

    # Cache and install cargo-llvm-cov
    - uses: actions/cache@v4
      if: inputs.cargo-llvm-cov == 'true'
      id: cache-cargo-llvm-cov
      with:
        path: ~/.cargo/bin/cargo-llvm-cov
        key: cargo-llvm-cov-0.6.18-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.cargo-llvm-cov == 'true' && steps.cache-cargo-llvm-cov.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-llvm-cov --version 0.6.18 --locked

    # Cache and install cargo-nextest
    - uses: actions/cache@v4
      if: inputs.cargo-nextest == 'true'
      id: cache-cargo-nextest
      with:
        path: ~/.cargo/bin/cargo-nextest
        key: cargo-nextest-0.9.103-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.cargo-nextest == 'true' && steps.cache-cargo-nextest.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-nextest --version 0.9.103 --locked

    # Cache and install cargo-workspaces
    - uses: actions/cache@v4
      if: inputs.cargo-workspaces == 'true'
      id: cache-cargo-workspaces
      with:
        path: |
          ~/.cargo/bin/cargo-workspaces
          ~/.cargo/bin/cargo-ws
        key: cargo-workspaces-0.4.0-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.cargo-workspaces == 'true' && steps.cache-cargo-workspaces.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-workspaces --version 0.4.0 --locked

    # Cache and install cargo-vet
    - uses: actions/cache@v4
      if: inputs.cargo-vet == 'true'
      id: cache-cargo-vet
      with:
        path: ~/.cargo/bin/cargo-vet
        key: cargo-vet-0.10.1-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.cargo-vet == 'true' && steps.cache-cargo-vet.outputs.cache-hit != 'true'
      run: |
        cargo install cargo-vet --version 0.10.1 --locked

    # Cache and install convco
    - uses: actions/cache@v4
      if: inputs.convco == 'true'
      id: cache-convco
      with:
        path: ~/.cargo/bin/convco
        key: convco-0.6.2-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.convco == 'true' && steps.cache-convco.outputs.cache-hit != 'true'
      run: |
        cargo install convco --version 0.6.2 --locked

    # Cache and install taplo-cli
    - uses: actions/cache@v4
      if: inputs.taplo-cli == 'true'
      id: cache-taplo-cli
      with:
        path: ~/.cargo/bin/taplo
        key: taplo-cli-0.10.0-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.taplo-cli == 'true' && steps.cache-taplo-cli.outputs.cache-hit != 'true'
      run: |
        cargo install taplo-cli --version 0.10.0 --locked

    # Cache and install trunk
    - uses: actions/cache@v4
      if: inputs.trunk == 'true'
      id: cache-trunk
      with:
        path: ~/.cargo/bin/trunk
        key: trunk-0.21.14-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.trunk == 'true' && steps.cache-trunk.outputs.cache-hit != 'true'
      run: |
        cargo install trunk --version 0.21.14 --locked

    # Cache and install mdbook
    - uses: actions/cache@v4
      if: inputs.mdbook == 'true'
      id: cache-mdbook
      with:
        path: ~/.cargo/bin/mdbook
        key: mdbook-0.4.52-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.mdbook == 'true' && steps.cache-mdbook.outputs.cache-hit != 'true'
      run: |
        cargo install mdbook --version 0.4.52 --locked

    # Cache and install just
    - uses: actions/cache@v4
      if: inputs.just == 'true'
      id: cache-just
      with:
        path: ~/.cargo/bin/just
        key: just-1.42.4-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.just == 'true' && steps.cache-just.outputs.cache-hit != 'true'
      run: |
        cargo install just --version 1.42.4 --locked

    # Cache and install fnm
    - uses: actions/cache@v4
      if: inputs.fnm == 'true'
      id: cache-fnm
      with:
        path: ~/.cargo/bin/fnm
        key: fnm-1.38.1-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.fnm == 'true' && steps.cache-fnm.outputs.cache-hit != 'true'
      run: |
        cargo install fnm --version 1.38.1 --locked

    # Cache and install wasm-pack
    - uses: actions/cache@v4
      if: inputs.wasm-pack == 'true'
      id: cache-wasm-pack
      with:
        path: ~/.cargo/bin/wasm-pack
        key: wasm-pack-0.13.1-${{ runner.os }}-${{ runner.arch }}
    - shell: bash
      if: inputs.wasm-pack == 'true' && steps.cache-wasm-pack.outputs.cache-hit != 'true'
      run: |
        cargo install wasm-pack --version 0.13.1 --locked
