[package]
name = "auto-renamed-crate"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[workspace]

[dependencies]
my-veecle-os-data-support-someip = { path = "../../../veecle-os-data-support-someip", package = "veecle-os-data-support-someip" }
