//! `veecle-telemetry-ui` is a visualizer for traces generated by Veecle OS applications.

#![forbid(unsafe_code)]

pub mod app;
mod command;
pub mod connection;
mod filter;
mod selection;
mod state;
mod store;
mod ui;
