[package]
name = "workspace"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Internal workspace tests"
homepage.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[package.metadata]
# We don't want to recursively test this (and it is purely a test helper crate).
workspace-checks.miri = false

[lib]
test = false

[[test]]
harness = false
name = "checks"

[dependencies]

[dev-dependencies]
camino = { workspace = true, features = ["serde"] }
cargo_metadata = { workspace = true }
libtest-mimic = { workspace = true }
serde_json = { workspace = true, features = ["std"] }
toml = { workspace = true, features = ["parse", "serde", "std"] }

[build-dependencies]
camino = { workspace = true, features = ["serde"] }
cargo_metadata = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }

[lints]
workspace = true
